# See https://github.com/dart-lang/mono_repo for details
dart:
  - stable
  - dev

stages:
  - analyze:
    - dartfmt
    - dartanalyzer: --fatal-infos --fatal-warnings .
  - publish_dry:
    - command: pub publish --dry-run
  - publish:
    - command: pub publish